# Generated by Django 6.0.2 on 2026-02-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintLocationGroupProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Complaint Grouped By Location & Type',
                'verbose_name_plural': 'Complaints Grouped By Location & Type',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaints.complaint',),
        ),
    ]
