# Generated by Django 6.0.2 on 2026-03-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaintlocationgroupproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='image_hash',
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='complaint',
            name='image_embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='predicted_class',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='issue_type',
            field=models.CharField(choices=[('pothole', 'Pothole'), ('garbage', 'Garbage'), ('streetlight', 'Streetlight'), ('water_leakage', 'Water Leakage'), ('drain', 'Drain'), ('other', 'Other')], max_length=20),
        ),
    ]
